In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
from scipy import integrate

Вариант 6.
1. Создать матрицу 10x10 из вещественных единиц. Создать
единичную матрицу 10x10.


In [4]:
# A = np.random.randint(0,10,(10, 10))

A= np.ones((10, 10),dtype=float) # создаем матрицу 10x10 из вещественных единиц
print(A)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Вычислить определитель ∣
2 1 3 6
4 1 3 3
5 2 4 1
5 1 2 2∣
.


In [3]:
import numpy as np

# создаем матрицу 10x10 из вещественных единиц
matrix = np.ones((10, 10))

# генерируем случайное целое число от 1 до 10
rand_int = np.random.randint(1, 11)

# умножаем матрицу на случайное целое число
matrix *= rand_int

print(matrix)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


3. Создать случайную матрицу A из целых чисел из отрезка
[-3,5] размера 4x4. Создать вектор-столбец B подходящего размера.
Решить систему AX = B.


4. Вычислить интеграл ∫
−1/2
1 /2
dx
√1− x
2
.


5. Вычислить интеграл ∫
0
+∞
cos2x dx .


6. Построить в одной системе координат графики функций:
{
y=sin ( x+π/ 3)
y=2x
. Оси координат должны быть подписаны,
графики должны быть разного цвета, должна быть выведена
легенда. Точку пересечения (если она есть) отметить на графике.